name: Report an issue with Blazing Macros application
description: Tell us if something is not working as expected
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for reaching out!
        Before submitting an issue please make sure that there isn't already an open issue describing the same problem.
  - type: dropdown
    id: package
    attributes:
      label: What Blazing Macros component has an issue
      options:
        - 'Others'
        - 'Workspaces'
        - 'Macros'
        - 'Mouse'
        - 'Keyboard'
        - 'Time'
        - 'Screen'
        - 'Function'
        - 'Actions'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What version of Blazing Macros are you using?
    validations:
      required: true