blank_issues_enabled: true
contact_links:
  - name: Feature request
    url: https://github.com/blazinginstruments/blazingmacros-issues/discussions/categories/feature-requests
    about: Request new feature
  - name: Ask a question, give feedback
    url: https://github.com/blazinginstruments/blazingmacros-issues/discussions/categories/general
    about: Connect with other community members with GitHub discussions
  - name: Get help on Discord
    url: https://discord.com/invite/MwXpcEWy4P
    about: Get help from the community on Discord