name: Report an issue with blazingmacros.com website
description: Nothing is perfect, especially the docs, help us find and fix mistakes, bad wording, etc.
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for reaching out!
        Before submitting an issue please make sure that there isn't already an open issue describing the same problem.
  - type: dropdown
    id: package
    attributes:
      label: What Blazing Macros Docs component has an issue
      options:
        - 'Documentation'
        - 'Sign Up/Login'
        - 'License'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
    validations:
      required: true